"""Seed data aligned with the V2.3.2 frontend mocks."""

from app.schemas.goals import Goal, GoalObservation, GoalPrediction, GoalSuggestion, Subgoal
from app.schemas.overview import ActivityItem, CalendarTask, OverviewCluster
from app.schemas.sources import IntegrationCatalogItem, Source
from app.schemas.tasks import ExecutionTask

SEED_GOALS: list[Goal] = [
    Goal(
        id="beijing-trip",
        title="Business Trip to Beijing Tomorrow",
        short="Beijing trip",
        status="Time-sensitive",
        progress=34,
        scheduleOffset=1,
        scheduledTime="08:30",
        description="Arrive in Beijing safely and protect the morning client meeting despite changing travel conditions.",
        sources=3,
        memories=4,
        outputs=2,
        tasks=3,
        completed=1,
        accent="255,94,0",
        category="Travel",
        updated="Live now",
        subgoals=[
            Subgoal(name="Check-in for flight CA1832", done=1, total=1, state="Completed"),
            Subgoal(name="Confirm hotel reservation in Chaoyang District", done=0, total=1, state="Needs action"),
            Subgoal(name="Review schedule for morning client meeting", done=0, total=1, state="At risk"),
        ],
        taskLabels=["Flight check-in", "Hotel confirmation", "Client meeting schedule"],
        recommendation="Move the trip to tonight or make the client meeting remote to reduce the weather-delay risk.",
        basis=["Weather feed", "Flight status", "Calendar"],
        observations=[
            GoalObservation(
                type="weather",
                title="Weather warning",
                detail="Heavy rain and thunderstorm warning forecasted for Beijing Capital Airport (PEK) tomorrow morning.",
                source="Beijing weather feed",
                time="2m ago",
            ),
            GoalObservation(
                type="flight",
                title="Flight status",
                detail="Flight CA1832 currently shows a 75% delay probability due to weather.",
                source="Live flight tracker",
                time="Now",
            ),
            GoalObservation(
                type="calendar",
                title="Calendar conflict",
                detail="Meeting scheduled at 10:00 AM immediately after the planned landing.",
                source="Work calendar",
                time="Live",
            ),
        ],
        prediction=GoalPrediction(
            probability=82,
            risk="HIGH RISK",
            title="A flight delay is likely to cause a missed morning meeting in Beijing.",
            impact="Client meeting",
            window="Tomorrow · 10:00 AM",
            confidence="High confidence",
        ),
        suggestions=[
            GoalSuggestion(
                id="earlier-flight",
                label="TRAVEL SAFEGUARD",
                title="Reschedule to tonight's 8:30 PM departure to arrive before the rainstorm.",
                action="Reschedule Flight",
                updates=0,
                options=["8:30 PM", "10:10 PM", "Compare all"],
            ),
            GoalSuggestion(
                id="remote-meeting",
                label="SCHEDULE SAFEGUARD",
                title="Shift tomorrow's 10:00 AM meeting to a remote video call.",
                action="Send Reschedule Request",
                updates=2,
                options=["Video call", "Move to 2 PM", "Draft only"],
            ),
        ],
    ),
    Goal(
        id="better-self",
        title="Become a Better Self",
        short="Better self",
        status="On track",
        progress=64,
        scheduleOffset=0,
        scheduledTime="09:00",
        description="Create sustainable progress across health, focused work, and continuous learning.",
        sources=9,
        memories=128,
        outputs=7,
        tasks=18,
        completed=11,
        accent="255,140,66",
        category="Wellbeing",
        updated="8m ago",
        subgoals=[
            Subgoal(name="Healthy living", done=5, total=7, state="Active"),
            Subgoal(name="Healthy work", done=4, total=6, state="Active"),
            Subgoal(name="Learning advancement", done=2, total=5, state="Planning"),
        ],
        taskLabels=[
            "Protect morning focus",
            "Complete strength session",
            "Review sleep pattern",
            "Read for 30 minutes",
            "Plan weekly reflection",
        ],
        recommendation="Move tomorrow's focus block 30 minutes earlier based on your recent energy pattern.",
        basis=["Fitness", "Calendar", "12 memories"],
        observations=[
            GoalObservation(
                type="context",
                title="Recovery trend",
                detail="Average sleep is 42 minutes below your confirmed target this week.",
                source="Apple Fitness",
                time="8m ago",
            ),
            GoalObservation(
                type="calendar",
                title="Focus window",
                detail="Tomorrow has an open 90-minute block before the first meeting.",
                source="Calendar",
                time="Live",
            ),
        ],
        prediction=GoalPrediction(
            probability=76,
            risk="OPPORTUNITY",
            title="Protecting the early focus window is likely to improve both work output and evening recovery.",
            impact="Energy balance",
            window="Tomorrow morning",
            confidence="Medium-high confidence",
        ),
        suggestions=[
            GoalSuggestion(
                id="protect-focus",
                label="ENERGY ALIGNMENT",
                title="Protect tomorrow's 8:30–10:00 AM window for the most important work.",
                action="Reserve Focus Block",
                updates=1,
                options=["8:00 AM", "8:30 AM", "Choose time"],
            ),
        ],
    ),
    Goal(
        id="spanish-fluency",
        title="Speak Spanish Confidently",
        short="Spanish fluency",
        status="Building momentum",
        progress=48,
        scheduleOffset=2,
        scheduledTime="19:00",
        description="Reach conversational confidence through daily practice and real-world speaking sessions.",
        sources=5,
        memories=36,
        outputs=4,
        tasks=16,
        completed=7,
        accent="139,92,246",
        category="Learning",
        updated="12m ago",
        subgoals=[
            Subgoal(name="Build daily vocabulary", done=5, total=7, state="Active"),
            Subgoal(name="Practice live conversation", done=1, total=5, state="Needs action"),
            Subgoal(name="Understand native media", done=1, total=4, state="Planning"),
        ],
        taskLabels=["Review 20 phrases", "Book conversation session", "Listen to a short podcast"],
        recommendation="A compatible conversation partner is available Wednesday evening. Review before matching.",
        basis=["Learning log", "Availability", "Goal history"],
        observations=[
            GoalObservation(
                type="context",
                title="Practice streak",
                detail="Vocabulary practice is consistent, but live speaking occurred only once this week.",
                source="Learning log",
                time="Today",
            ),
        ],
        prediction=GoalPrediction(
            probability=73,
            risk="PLATEAU RISK",
            title="Progress will likely plateau unless passive learning is converted into live speaking practice.",
            impact="Speaking confidence",
            window="Next 2 weeks",
            confidence="High confidence",
        ),
        suggestions=[
            GoalSuggestion(
                id="book-speaking",
                label="ACTIVE PRACTICE",
                title="Book a 30-minute Spanish conversation session for Wednesday evening.",
                action="Book Practice",
                updates=1,
                options=["6:30 PM", "7:30 PM", "Find partner"],
            ),
        ],
    ),
    Goal(
        id="financial-resilience",
        title="Build Financial Resilience",
        short="Financial resilience",
        status="Needs review",
        progress=37,
        description="Create a reliable safety buffer and make long-term spending decisions with confidence.",
        sources=6,
        memories=22,
        outputs=3,
        tasks=12,
        completed=4,
        accent="255,183,3",
        category="Finance",
        updated="21m ago",
        subgoals=[
            Subgoal(name="Establish an emergency fund", done=2, total=5, state="Active"),
            Subgoal(name="Understand recurring spending", done=2, total=4, state="Review"),
            Subgoal(name="Create an investment routine", done=0, total=3, state="Planning"),
        ],
        taskLabels=["Review monthly ledger", "Confirm savings target", "Classify recurring expenses"],
        recommendation="Three recurring expenses changed this month. Review them before updating the savings plan.",
        basis=["Family ledger", "Transactions", "2 memories"],
        observations=[
            GoalObservation(
                type="context",
                title="Savings pace",
                detail="This month's emergency-fund contribution is 18% below the confirmed plan.",
                source="Family ledger",
                time="21m ago",
            ),
        ],
        prediction=GoalPrediction(
            probability=69,
            risk="PLAN DRIFT",
            title="At the current contribution pace, the emergency-fund milestone may be delayed by six weeks.",
            impact="Safety buffer",
            window="Next 3 months",
            confidence="Medium confidence",
        ),
        suggestions=[
            GoalSuggestion(
                id="review-costs",
                label="SPENDING REVIEW",
                title="Review the three changed subscriptions before Friday's plan update.",
                action="Open Cost Review",
                updates=1,
                options=["Review now", "Friday 6 PM", "Export list"],
            ),
        ],
    ),
    Goal(
        id="family-connections",
        title="Strengthen Family Connections",
        short="Family connections",
        status="Healthy",
        progress=81,
        description="Stay meaningfully connected through shared time, thoughtful follow-up, and family rituals.",
        sources=7,
        memories=84,
        outputs=6,
        tasks=11,
        completed=9,
        accent="255,124,89",
        category="Relationships",
        updated="1h ago",
        subgoals=[
            Subgoal(name="Protect weekly family time", done=4, total=4, state="Completed"),
            Subgoal(name="Stay present across distance", done=3, total=4, state="Active"),
            Subgoal(name="Preserve shared memories", done=2, total=3, state="Active"),
        ],
        taskLabels=["Confirm Sunday dinner", "Call parents", "Organize recent photos"],
        recommendation="Sunday afternoon is open for everyone. Review a proposed family plan before sending.",
        basis=["Family calendar", "Photos", "8 memories"],
        observations=[
            GoalObservation(
                type="calendar",
                title="Shared availability",
                detail="Sunday afternoon is the only shared open window across the family calendar.",
                source="Family calendar",
                time="Live",
            ),
        ],
        prediction=GoalPrediction(
            probability=84,
            risk="POSITIVE WINDOW",
            title="A protected Sunday plan is highly likely to strengthen connection without disrupting other commitments.",
            impact="Shared family time",
            window="This Sunday",
            confidence="High confidence",
        ),
        suggestions=[
            GoalSuggestion(
                id="family-plan",
                label="SHARED TIME",
                title="Draft a simple Sunday family plan using the shared afternoon window.",
                action="Review Family Plan",
                updates=0,
                options=["Lunch", "Afternoon", "Evening"],
            ),
        ],
    ),
]

SEED_SOURCES: list[Source] = [
    Source(
        id="iphone",
        name="Xiaomi Phone",
        category="device",
        type="Personal device",
        method="Local device bridge",
        status="Connected",
        statusType="connected",
        lastSync="2m ago",
        assets="286 signals",
        scopes=["App activity", "Selected photos", "Device health"],
        purposes=["Daily context", "Goal support"],
        usedBy="Morning brief · 09:10",
    ),
    Source(
        id="macbook",
        name="Work Laptop",
        category="device",
        type="Personal device",
        method="Encrypted LAN",
        status="Connected",
        statusType="connected",
        lastSync="6m ago",
        assets="42 work items",
        scopes=["Selected folders", "Work activity"],
        purposes=["Project planning"],
        usedBy="Product recommendation · Now",
    ),
    Source(
        id="dashcam",
        name="Dash Cam",
        category="device",
        type="Storage device",
        method="USB connection",
        status="Needs attention",
        statusType="attention",
        lastSync="Failed 1h ago",
        assets="0 new assets",
        scopes=["Selected recordings"],
        purposes=["Travel archive"],
        usedBy="No AI task used this source",
    ),
    Source(
        id="documents",
        name="Personal Documents",
        category="files",
        type="Files & folders",
        method="Explicit local selection",
        status="Connected",
        statusType="connected",
        lastSync="12m ago",
        assets="124 files",
        scopes=["Selected documents"],
        purposes=["Local semantic search"],
        usedBy="Research summary · Today",
    ),
    Source(
        id="research",
        name="Product Research",
        category="files",
        type="Knowledge materials",
        method="Watched local folder",
        status="Processing",
        statusType="processing",
        lastSync="Processing now",
        assets="38 notes",
        scopes=["Research folder"],
        purposes=["Product goal"],
        usedBy="Prototype recommendation · Now",
    ),
    Source(
        id="calendar",
        name="Google Calendar",
        category="productivity",
        type="Calendar & productivity",
        method="Live",
        status="Ready to connect",
        statusType="idle",
        lastSync="Not connected",
        assets="0 events",
        scopes=["Event title", "Time & availability"],
        purposes=["Planning", "Reminders"],
        usedBy="Connect from Import Data catalog",
        connectionId=None,
    ),
    Source(
        id="notion",
        name="Notion Workspace",
        category="productivity",
        type="Productivity service",
        method="MCP extension",
        status="Connected",
        statusType="connected",
        lastSync="14m ago",
        assets="62 pages",
        scopes=["Selected workspace"],
        purposes=["Project context"],
        usedBy="Weekly review · Yesterday",
        connectionId="conn-notion",
    ),
    Source(
        id="fitness",
        name="Apple Fitness",
        category="health",
        type="Health & lifestyle",
        method="Account authorization",
        status="Connected",
        statusType="connected",
        lastSync="8m ago",
        assets="42 metrics",
        scopes=["Activity", "Sleep summary"],
        purposes=["Health goal"],
        usedBy="Recovery insight · 08:40",
    ),
    Source(
        id="identity",
        name="Digital Identity",
        category="identity",
        type="Public identity candidates",
        method="Maigret discovery",
        status="Review required",
        statusType="attention",
        lastSync="Yesterday",
        assets="4 candidates",
        scopes=["Public usernames only"],
        purposes=["Identity review"],
        usedBy="Not available to AI until confirmed",
    ),
    Source(
        id="wechat",
        name="WeChat",
        category="communication",
        type="Communication data",
        method="Authorized adapter",
        status="Connected",
        statusType="connected",
        lastSync="21m ago",
        assets="Selected conversations",
        scopes=["Chosen chats only"],
        purposes=["Relationship context"],
        usedBy="Family reminder · Yesterday",
    ),
    Source(
        id="drive",
        name="Cloud Drive",
        category="files",
        type="Third-party service",
        method="Official API",
        status="Connected",
        statusType="connected",
        lastSync="33m ago",
        assets="86 files",
        scopes=["Selected folders"],
        purposes=["Document retrieval"],
        usedBy="Meeting preparation · Today",
    ),
    Source(
        id="web",
        name="DeepSearch",
        category="identity",
        type="External public information",
        method="On-demand tool",
        status="Available on demand",
        statusType="idle",
        lastSync="Never runs automatically",
        assets="0 retained results",
        scopes=["Per-task query only"],
        purposes=["Current research"],
        usedBy="External use always disclosed",
    ),
]


def _catalog(
    key: str,
    name: str,
    category: str,
    method: str,
    description: str,
    scopes: list[str],
    auth_type: str,
    nango_provider_key: str | None = None,
) -> IntegrationCatalogItem:
    return IntegrationCatalogItem(
        id=key,
        name=name,
        category=category,
        method=method,
        description=description,
        scopes=scopes,
        authType=auth_type,
        nangoProviderKey=nango_provider_key,
    )


INTEGRATION_CATALOG: list[IntegrationCatalogItem] = [
    _catalog(
        "local-device-bridge",
        "Local device bridge",
        "device",
        "Encrypted local bridge",
        "Connect a phone, laptop, or USB device through an encrypted local bridge.",
        ["Selected device categories"],
        "api_key",
    ),
    _catalog(
        "local-folder",
        "Local folder",
        "files",
        "Explicit local selection",
        "Import only the files and folders you choose.",
        ["Selected documents"],
        "api_key",
    ),
    _catalog(
        "google-drive",
        "Google Drive",
        "files",
        "Coming soon",
        "Sync selected folders for document retrieval.",
        ["Selected folders"],
        "api_key",
    ),
    _catalog(
        "google-calendar",
        "Google Calendar",
        "productivity",
        "Live",
        "Sync events and availability for planning.",
        ["Event title", "Time & availability"],
        "nango",
        "google-calendar",
    ),
    _catalog(
        "notion",
        "Notion",
        "productivity",
        "Live",
        "Import selected workspace pages.",
        ["Selected workspace"],
        "nango",
        "notion",
    ),
    _catalog(
        "github",
        "GitHub",
        "productivity",
        "Coming soon",
        "Read selected repositories for project context.",
        ["Selected repositories"],
        "api_key",
    ),
    _catalog(
        "linear",
        "Linear",
        "productivity",
        "Coming soon",
        "Track issues and project status.",
        ["Issue titles", "Status"],
        "api_key",
    ),
    _catalog(
        "slack",
        "Slack",
        "productivity",
        "Coming soon",
        "Connect selected channels for work context.",
        ["Selected channels"],
        "api_key",
    ),
    _catalog(
        "apple-fitness",
        "Apple Fitness",
        "health",
        "Coming soon",
        "Import activity and sleep summaries.",
        ["Activity", "Sleep summary"],
        "api_key",
    ),
    _catalog(
        "deepsearch",
        "DeepSearch",
        "identity",
        "MCP URL",
        "Public research queries that never run automatically.",
        ["Per-task query only"],
        "mcp_url",
    ),
    _catalog(
        "wechat",
        "微信 WeChat",
        "communication",
        "API key",
        "[中国] Import chosen chats for relationship context.",
        ["Chosen chats only"],
        "api_key",
    ),
    _catalog(
        "telegram",
        "Telegram",
        "communication",
        "AstrBot",
        "Connect Telegram as a messaging source (AstrBot sidecar).",
        ["Authorized chats"],
        "astrbot",
    ),
    _catalog(
        "discord",
        "Discord",
        "communication",
        "AstrBot",
        "Connect Discord as a messaging source (AstrBot sidecar).",
        ["Authorized servers"],
        "astrbot",
    ),
    _catalog(
        "gmail",
        "Gmail",
        "productivity",
        "Coming soon",
        "Read selected mail for scheduling and follow-up context.",
        ["Selected labels"],
        "api_key",
    ),
]

# Expand with China-first + global long-tail from fixtures/connectors.json.
from app.services.connector_catalog import merge_catalog  # noqa: E402

INTEGRATION_CATALOG = merge_catalog(INTEGRATION_CATALOG)

CATALOG_SOURCE_IDS: dict[str, str] = {
    "local-device-bridge": "iphone",
    "local-folder": "documents",
    "google-drive": "drive",
    "google-calendar": "calendar",
    "notion": "notion",
    "apple-fitness": "fitness",
    "deepsearch": "web",
    "wechat": "wechat",
    "telegram": "telegram",
    "discord": "discord",
    "feishu": "feishu",
    "dingtalk": "dingtalk",
    "wecom": "wecom",
    "wecom-ai": "wecom-ai",
    "qq": "qq",
    "github": "github",
    "linear": "linear",
    "slack": "slack",
    "gmail": "gmail",
}

SOURCE_CATALOG_KEYS: dict[str, str] = {
    source_id: catalog_key for catalog_key, source_id in CATALOG_SOURCE_IDS.items()
}

SEED_TASKS: list[ExecutionTask] = [
    ExecutionTask(
        id="task-1",
        goalId="beijing-trip",
        name="Confirm hotel reservation in Chaoyang District",
        state="Needs action",
        dueAt="+0T14:00",
        subgoalName="Confirm hotel reservation in Chaoyang District",
        owner="human",
    ),
    ExecutionTask(
        id="task-2",
        goalId="better-self",
        name="Protect morning focus",
        state="Active",
        dueAt="+0T09:30",
        subgoalName="Healthy work",
        owner="human",
    ),
    ExecutionTask(
        id="task-3",
        goalId="spanish-fluency",
        name="Book conversation session",
        state="Needs action",
        dueAt="+1T19:00",
        subgoalName="Practice live conversation",
        owner="human",
    ),
    ExecutionTask(
        id="task-4",
        goalId="financial-resilience",
        name="Review monthly ledger",
        state="Active",
        dueAt="+2T16:00",
        subgoalName="Understand recurring spending",
        owner="human",
    ),
    ExecutionTask(
        id="task-5",
        goalId="family-connections",
        name="Confirm Sunday dinner",
        state="Active",
        dueAt="+3T18:00",
        subgoalName="Protect weekly family time",
        owner="human",
    ),
    ExecutionTask(
        id="task-ai-1",
        goalId="better-self",
        name="Morning priorities prepared",
        state="Completed",
        dueAt="+0T08:15",
        subgoalName="Healthy work",
        owner="ai",
    ),
    ExecutionTask(
        id="task-ai-2",
        goalId="beijing-trip",
        name="Travel brief assembled",
        state="Completed",
        dueAt="+0T07:45",
        subgoalName="Review schedule for morning client meeting",
        owner="ai",
    ),
    ExecutionTask(
        id="task-ai-3",
        goalId="financial-resilience",
        name="Spending anomalies flagged",
        state="Needs confirmation",
        dueAt="+0T11:00",
        subgoalName="Understand recurring spending",
        owner="ai",
    ),
    ExecutionTask(
        id="task-ai-4",
        goalId="spanish-fluency",
        name="Practice deck drafted",
        state="Needs confirmation",
        dueAt="+1T15:30",
        subgoalName="Practice live conversation",
        owner="ai",
    ),
    ExecutionTask(
        id="task-6",
        goalId="better-self",
        name="Client Meeting",
        state="Needs action",
        dueAt="+0T14:00",
        subgoalName="Healthy work",
        owner="human",
    ),
    ExecutionTask(
        id="task-7",
        goalId="family-connections",
        name="Send weekend check-in",
        state="Needs action",
        dueAt="+2T12:30",
        subgoalName="Protect weekly family time",
        owner="human",
    ),
    ExecutionTask(
        id="task-ai-5",
        goalId="family-connections",
        name="Family context retrieved",
        state="Completed",
        dueAt="+1T10:00",
        subgoalName="Protect weekly family time",
        owner="ai",
    ),
    ExecutionTask(
        id="task-8",
        goalId="beijing-trip",
        name="Pack travel documents",
        state="Needs action",
        dueAt="+1T21:00",
        subgoalName="Review schedule for morning client meeting",
        owner="human",
    ),
    ExecutionTask(
        id="task-ai-6",
        goalId="better-self",
        name="Recovery plan prepared",
        state="Active",
        dueAt="+2T08:00",
        subgoalName="Healthy work",
        owner="ai",
    ),
    ExecutionTask(
        id="task-9",
        goalId="spanish-fluency",
        name="Review vocabulary set",
        state="Active",
        dueAt="+3T09:00",
        subgoalName="Practice live conversation",
        owner="human",
    ),
    ExecutionTask(
        id="task-ai-7",
        goalId="financial-resilience",
        name="Budget checkpoint drafted",
        state="Active",
        dueAt="+3T11:30",
        subgoalName="Understand recurring spending",
        owner="ai",
    ),
]

OVERVIEW_CLUSTERS: list[OverviewCluster] = [
    OverviewCluster(key="goals", title="Goal Management", count=5),
    OverviewCluster(key="data", title="Personal Data", count=12),
    OverviewCluster(key="memory", title="Long-term Memory", count=128),
]

SEED_ACTIVITY: list[ActivityItem] = [
    ActivityItem(
        id="act-1",
        label="Morning brief",
        detail="3 goals need attention today",
        route="goals",
        timestamp="Now",
    ),
    ActivityItem(
        id="act-2",
        label="Personal data synchronized",
        detail="Connected sources are ready for authorized tasks",
        route="import-data",
        timestamp="8m",
    ),
]

OVERVIEW_ACTIVITY = SEED_ACTIVITY

OVERVIEW_CALENDAR: list[CalendarTask] = [
    CalendarTask(
        id="cal-tomorrow-ai",
        title="Beijing day pack prepared",
        time="06:30",
        dayOffset=1,
        owner="ai",
        label="AI IS PREPARING",
        detail="Itinerary and documents for tomorrow",
        status="Preparing",
        type="planning",
        goalId="beijing-trip",
        icon="clock",
    ),
    CalendarTask(
        id="cal-day2-ai",
        title="Spanish practice plan",
        time="18:00",
        dayOffset=2,
        owner="ai",
        label="AI PLANNING",
        detail="Conversation prompts for this week",
        status="Planned",
        type="planning",
        goalId="spanish-fluency",
        icon="spark",
    ),
    CalendarTask(
        id="cal-day3-human",
        title="Weekly review block",
        time="17:00",
        dayOffset=3,
        owner="human",
        label="YOUR TASK",
        detail="Protect time to review goal progress",
        status="To do",
        type="action",
        goalId="better-self",
        icon="target",
    ),
]

ADMIN_USER_ID = "dev-user"
